config/routes.rb
Rails.application.routes.draw do
  
  #----------------------------------#
  # Gift Garden Routes File
  # original written by: Andy W, Oct 14 2016
  # major contributions by:
  #             Wei H, Oct 16 2016
  #----------------------------------#
  
  resources :gifts, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :donors, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :activities, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/reports', to: 'static_pages#reports'
  get    '/import-export', to: 'static_pages#import_export'
  
  get    'hyper-surf/donors', to: 'hyper_surf#donors'
  get    'hyper-surf/all', to: 'hyper_surf#all'
  
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
  #----------------------------------#
  # Static Pages Controller
  # original written by: Jason K, Oct 17 2016
  # major contributions by:
  #
  #----------------------------------#
  
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
  
  def contact
  end
  
  def reports
    @activities = Activity.all
  end
  
  def import_export
    @activities = Activity.all
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
  <!-- Content Header -->
  <div class="row">
    <div class="col-sm-10 col-xs-offset-2">
      <div class="page-header">
        <h2>About</h2>
      </div>
    </div>
  </div>
  <!-- Content -->
  <div class="row col-xs-offset-2">
    <h3>Paths</h3> Static Pages Controller
    <ul>
      <li>
        <%=link_to "Front Page", root_path %>
      </li>
      <li>
        <%=link_to "About", about_path %>
      </li>
      <li>
        <%=link_to "Help", help_path %>
      </li>
      <li>
        <%=link_to "Contact", contact_path %>
      </li>
      <li>
        <%=link_to "Import Export", import_export_path %>
      </li>
      <li>
        <%=link_to "Reports", reports_path %>
      </li>
    </ul>
    Import Export Controller
    <ul>
      <li>
        <%=link_to "Requested via Import Export Page", import_export_path %>
      </li>
    </ul>
    Activities Controller
    <ul>
      <li>
        <%=link_to "All Activities", activities_path %>
      </li>
      <li>
        <%=link_to "Create Activity", new_activity_path %>
      </li>
      <li>
        <%=link_to "Edit Activity (ID: 1)", edit_activity_path(:id=> "1") %></li>
    </ul>
    Donors Controller
    <ul>
      <li>
        <%=link_to "All Donors", donors_path %>
      </li>
      <li>
        <%=link_to "Create Donor", new_donor_path %>
      </li>
      <li>
        <%=link_to "Donor (ID: 2)", edit_donor_path(:id=> "2") %></li>
    </ul>
    Gifts Controller
    <ul>
      <li>
        <%=link_to "All Gifts", gifts_path %>
      </li>
      <li>
        <%=link_to "Create Gift", new_gift_path %>
      </li>
      <li><%=link_to "Edit Gift (ID: 5)", edit_gift_path(:id=> "5") %></li>
    </ul>
    HyperSurf
    <ul>
      <li><%=link_to "General Surf", hyper_surf_all_path %></li>
      <li><%=link_to "Donor Surf", hyper_surf_donors_path %></li>
    </ul>


    <h3>Information Fill</h3>
    <p>Welcome To Donna Donor! A web application built by North Central College CSC 694 Class of Fall 2016!</p>

    <b>Team</b>
    <ul>
      <li>Bill K</li>
      <li>Andy W</li>
      <li>Mike D</li>
      <li>Pat M</li>
      <li>Wei H</li>
      <li>Jason K</li>
    </ul>
    <div style="height: 900px;">
      &nbsp;
    </div>
  </div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="row">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Contact</h2>
  	</div>
  	<div class='row col-xs-offset-0'>
  	  <p>Thank you for your interest in our application! We appreciate your support.</p>
      <p>Please contact the management at <b><a href='mailto:wtkrieger@noctrl.edu'>
        wtkrieger@noctrl.edu</a></b>.</p>
      <p>Our office is located at North Central College in Naperville.</p>
  	</div>
  	<aside>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2975.4631596931986!2d-88.14545388495804!3d41.77523097923049!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e57ba0680c581%3A0xec886aa9cf5f8824!2sCarnegie+Hall%2C+10+N+Brainard+St%2C+Naperville%2C+IL+60540!5e0!3m2!1sen!2sus!4v1476557455365" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  	</aside>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="row">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Help</h2>
  	</div>
  </div>
</div>
<div class="row col-xs-offset-2">
    <p>Welcome To Gift Garden!  A web application built by North Central College CSC
    694 Class of Fall 2016!</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 ">
      <div class="jumbotron well">
        <h2>Welcome to Gift Garden</h2>
        <p>
          Select one of the 4 basic actions to 1) Add new gifts, 2) "Surf" means view/edit information online, 3) Create formatted reports, and 4) Import/export data.
          <br>
        </p>
      </div>
      <!-- jumbotron -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
  <div class="row row-donna-home-icons ">
    <div class="col-xs-12 col-sm-4 col-sm-offset-2">
      <%=link_to(new_gift_path) do %>
        <span class="glyphicon glyphicon-plus icon-donna icon-donna-new"></span><span class="icon-donna-text">New Gifts</span>
        <% end %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%=link_to(reports_path) do %>
        <span class="glyphicon glyphicon-print icon-donna icon-donna-reports"></span><span class="icon-donna-text">Reports</span>
        <% end %>
    </div>
  </div>
  <div class="row row-donna-home-icons ">
    <div class="col-xs-12 col-sm-4 col-sm-offset-2">
      <%=link_to(activities_path ) do %>
        <span class="glyphicon glyphicon-thumbs-up icon-donna icon-donna-surf"></span><span class="icon-donna-text">Surf!</span>
        <% end %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%=link_to(import_export_path) do %>
        <span class="glyphicon glyphicon-transfer icon-donna icon-donna-importexport"></span><span class="icon-donna-text">Import/Export</span>
        <% end %>
    </div>
  </div>

app/views/static_pages/import_export.html.erb
<% provide(:title, "Import-Export Information") %>
<div class="overlay" id="overlay" style="display:none;"></div>
<div class="row">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class='import-header'>
  		<h2 class="import-color">Import <small>&nbsp; read data into Donna Donor from an outside source</small></h2>
  	</div>
  </div>
</div>

<!-- Import content -->
  <div class="row report-row">
    <div class="col-xs-8 col-xs-offset-2" id='inKindLink'> 
    <%= link_to('import-export/inkind') do %>
    	<span class="	glyphicon glyphicon-leaf import-icon import-color"></span>
    	<span class="report-title">In-kind</span> 
  	<% end %>
    	<span class="report-description">- import non-cash, in-kind donations</span> 
    </div>
  </div>

<!-- Beginning of CSV Imports -->
<div class="row  report-row">
  <div class="col-xs-8 col-xs-offset-2" id="importLink"> 
  <%= link_to('javascript:void(0)') do %>
  	<span class="	glyphicon glyphicon-download import-icon import-color"></span>
  	<span class="report-title">CSV Import</span> 
  	<% end %>
  	<span class="report-description">- import data from Raiser's Edge</span> 
  </div>
</div>

<div id='inKindPopupWrapper' class='import-export-dialog import-export-text'>
	<a class="boxclose" id="boxclose"></a>
	<br />
	<div id='inKindImportDiv' class='import-html'>
  	<p>
  		<div>Imports will be created from the chosen .csv file.<br /></div>
		  <br />
		  <button type="button" onclick="alert('import in kind data')">Import In Kind Data</button>
		  <br />
  	</p>
  </div>		
</div>

															<!-- col-xs-8 col-xs-offset-2 -->
<div id='importPopupWrapper' class='import-export-dialog import-export-text'>
	<a class="boxclose" id="boxclose"></a>
	<br/>
	<div class='import-export-label'>
		<span>Please select the import type:</span>
    <select id="importTypeSelection" name="user_id">
      <option value="None" selected="selected">Choose Type</option>
      <option value="Donors">Donors</option></option>
      <option value="Gifts">Gifts</option>
    </select>
	</div>
  	
	<div id='donorsImportDiv' class='import-html import-export-label'>
		<br />
		<%= form_tag import_donors_path, multipart: true do %>
      <%= file_field_tag :file %>
      <br />
      <%= submit_tag "Import Donors from CSV" %>
  	<% end %>
  </div>
  
  <div id='giftsImportDiv' class='import-html import-export-label'>
  	<p>
  		<%= form_tag import_gifts_path, multipart:true do %>
  			<span>Choose associated activity:</span>
  			<%= select_tag "activity",
  			options_from_collection_for_select(@activities, "id", "name") %>
  			
  			<br /><br />
	      <%= file_field_tag :file %>
	      <br />
	      <%= submit_tag "Import Gifts from CSV" %>
    	<% end %>
  	</p>
  </div>
</div> 

</div>	<!-- End of CSV Imports -->

<!-- Export header -->
<div class="row export-header">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class='import-header'>
  		<h2 class="export-color">Export <small>&nbsp; write data out of the program</small></h2>
  	</div>
  </div>
</div>   <!-- row -->

<!-- Export content -->
<div class="row report-row">
	<div class="col-xs-8 col-xs-offset-2"> 
	<%= link_to('import-export/export.csv') do %>
	<%= icon("envelope", class: "report-icon export-icon export-color") %>
	<span class="report-title">MailChimp</span>
	<% end %>
	<span class="report-description">- export contact info to MailChimp</span> 
	</div>
</div>

<div class="row report-row">
	<div class="col-xs-8 col-xs-offset-2"> 
	<%= link_to('import-export/export.csv') do %>
	<%= icon("envelope", class: "report-icon export-icon export-color") %>
	<span class="report-title">Contstant Contact</span>
	<% end %>
	<span class="report-description">- export contact info to Constant Contact</span> 
	</div>
</div>

<script>
	$(document).ready(function() {
		$("#inKindPopupWrapper").css('display', 'none');
		$("#importPopupWrapper").css('display', 'none');
		
		$("#inKindLink").click(function () {
			$('#overlay').fadeIn(200,function(){
           $('#inKindPopupWrapper').animate({
						opacity: "toggle",
						height: "toggle"
					}); 
        });
			return false;
		});
		
		$("#importLink").click(function () {
			$('#overlay').fadeIn(200,function(){
           $('#importPopupWrapper').animate({
						opacity: "toggle",
						height: "toggle"
					}); 
        });
			importFunctions.hideImports();
			return false;
		});
		
		$('.boxclose').click(function(){
			hideImportDialogAndOverlay();
    });
			
    $(document).keyup(function(e) {
     	if (e.keyCode == 27) {	// esc pressed
        if ($(".import-export-dialog").length ||
        		$(".boxclose").length ||
        		$(".overlay").length) {
        		hideImportDialogAndOverlay();		
    		}
    	}
		});
		
		$('#importTypeSelection').on('change', function() {
      if (this.value == 'Donors') {
        importFunctions.hideImports();
        $('#donorsImportDiv').toggle();
      }
      else if (this.value == 'Gifts') {
        importFunctions.hideImports();
        $('#giftsImportDiv').toggle();
      }
    });
    
    if($("div.alert.alert-info").length) {
			  setTimeout(function(){ 
			  	$("div.alert.alert-info").fadeOut("slow") }, 2000);
			} 
    
	});
	
	function hideImportDialogAndOverlay () {
		if ($('#inKindPopupWrapper').css('display') == 'block') {
				$('#inKindPopupWrapper').animate({
					opacity: "toggle",
					height: "toggle"
				});
			}
			
    	if ($('#importPopupWrapper').css('display') == 'block') {
				$('#importPopupWrapper').animate({
					opacity: "toggle",
					height: "toggle"
				});
			}
			
    	$('#overlay').fadeOut('fast');
	}
	
</script>

app/views/static_pages/reports.html.erb
<% provide(:title, "Reports") %>
<div class="overlay" id="overlay" style="display:none;"></div>
<div class="row">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Reports <small>&nbsp; These executive reports are quickly and easily created. 
	  		The output of each report is a nicely-formatted PDF file.</small></h2>
  	</div>
  </div>
</div>
<!-- Content -->
  <div class="row report-row" id="activity-report">
    <div class="col-xs-8 col-xs-offset-2">
      <%= link_to('activities.pdf') do %> <!-- 'javascript:void(0)' -->
    	  <%= icon("ship", class: "report-icon") %>
    	  <span class="report-title">Activity</span>
    	<% end %>
    	<span class="report-description">- report the donors and gifts for an Activity</span>
    </div>
  </div>

  <div class="row report-row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= link_to('donors.pdf') do %>
  		  <span class="glyphicon glyphicon-phone-alt report-icon"></span>
  		  <span class="report-title">Donor</span>
  		<% end %>
    	<span class="report-description">- report donations of a single Donor</span>
    </div>
  </div>

  <div class="row report-row">
    <div class="col-xs-8 col-xs-offset-2"> 
    <%= link_to('gifts.pdf') do %>
    	  <%= icon("gift", class: "report-icon") %>
    	  <span class="report-title">Gifts</span>
    	<% end %>
    	<span class="report-description">- report all Gifts over a time period</span> 
    </div>
  </div>

  <div class="row report-row">
    <div class="col-xs-8 col-xs-offset-2"> 
    <%= link_to('activities.pdf') do %>
	      <span class="glyphicon glyphicon-repeat report-icon"></span>
	      <span class="report-title">Recurring Activity</span>
	    <% end %>
	    <span class="report-description">- report annual comparison of a recurring activity</span>
    </div>
  </div>
  
  <div class="row report-row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= link_to('donors.pdf') do %> 
        <%= icon("calendar-check-o", class: "report-icon") %>
        <span class="report-title">LYBUNT</span>
      <% end %>
      <span class="report-description">- report Donors who gave last year but unfortunately not this year</span>
    </div>
  </div>
  
  <!-- Dialog Content -->
<div id='importPopupWrapper' class='import-export-dialog import-export-text'>
   <a class="boxclose" id="boxclose"></a>
   <div class='import-export-label' id="activity-report-dialog">
      <p>
         <%= form_tag 'activities.pdf' do %>
         <span>Choose Activity:</span>
         <br /><br />
         <%= select_tag "activity",
            options_from_collection_for_select(@activities, "id", "name") %>
         <br /><br />
         <%= submit_tag "Generate Report" %>
         <% end %>
      </p>
   </div>
</div>

<script>
   $(document).ready(function() {
     $("#importPopupWrapper").css("display", "none");
     hideImportDialogAndOverlay();
     
     $('.boxclose').click(function(){
   	hideImportDialogAndOverlay();
     });
     
     $(document).keyup(function(e) {
      	if (e.keyCode == 27) {	// esc pressed
         if ($(".import-export-dialog").length ||
         		$(".boxclose").length ||
         		$(".overlay").length) {
         		hideImportDialogAndOverlay();		
     		}
     	}
   });
   });
   
   //$("#activity-report").click(function() {
       //showOverlay();
       //$('#importPopupWrapper').animate({
   	//			opacity: "toggle",
   	//			height: "toggle"
   	//}); 
   	//$("#activity-report-dialog").css("display", "block");
     //});
   
   function showOverlay() {
     $('#overlay').fadeIn(200);
   }
   
   function hideImportDialogAndOverlay () {
     	if ($('#importPopupWrapper').css('display') == 'block') {
   		$('#importPopupWrapper').animate({
   			opacity: "toggle",
   			height: "toggle"
   		});
   	}
   	
     	$('#overlay').fadeOut('fast');
   }
   
</script>