config/routes.rb
Rails.application.routes.draw do
  
  #----------------------------------#
  # Gift Garden Routes File
  # original written by: Andy W, Oct 14 2016
  # major contributions by:
  #             Wei H, Oct 16 2016
  #----------------------------------#
  
  resources :gifts, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :donors, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :activities, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/reports', to: 'static_pages#reports'
  get    '/import-export', to: 'static_pages#import_export'
  
  get    'hyper-surf/donors', to: 'hyper_surf#donors'
  get    'hyper-surf/all', to: 'hyper_surf#all'
  
  root 'static_pages#home'
end

app/models/donor.rb
class Donor < ApplicationRecord
  #----------------------------------#
  # Donors Model Definition
  # original written by: Andy W, Oct 13 2016
  # major contributions by:
  #             Wei H, Oct 15 2016
  #             Pat M, Oct 17 2016
  #----------------------------------#
  
  has_many :gifts, dependent: :destroy
  default_scope -> {order(created_at: :desc)}
  validates :first_name, presence: true, length: {maximum:50}
  validates :last_name, presence: true, length: {maximum:50}
  validates :address, presence: true
  validates :city, presence: true, length: {maximum:30}
  validates :state, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  require 'csv'
  
  # Export Donors
  # outputs all donors as a csv file(all attributes included).
  def self.as_csv
    CSV.generate do |csv|
    csv << column_names
    all.each do |item|
      csv << item.attributes.values_at(*column_names)
      end
    end
  end
  
  # Import Donors
  # Takes csv file and by row seeks to update or add in donor(s).
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      donor_hash = row.to_hash # exclude the price field
      donor = Donor.where(id: donor_hash["id"])

      if donor.count == 1
        donor.first.update_attributes(donor_hash)
      else
        Donor.create!(donor_hash)
      end # end if else
    end # end foreach
  end
  
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
 #----------------------------------#
  # GiftGarden Donors Controller
  # original written by: Andy W, Oct 17 2016
  # major contributions by:
  #         
  #----------------------------------#
 
 # creates new donor object for New Donor screen
  def new
    @donor = Donor.new
  end
  
  # populates Edit Donor screen with data for the correct donor id
  def edit
    @donor = Donor.find(params[:id])
  end
  
  # creates new donor with permitted donor params defined below in private section
  # or renders for again with error messages
  def create
    @donor = Donor.new(donor_params)
    if @donor.save
      flash[:success] = "Activty added successfully!"
      redirect_to donors_url
    else
      render 'new'
    end
  end
  
  # updates donor information or renders update form again with error messages
  def update
    @donor = Donor.find(params[:id])
    if @donor.update(donor_params)
       redirect_to donors_url
      flash[:success] = "Donor updated successfully!"
    else
      render 'edit'
    end
  end
  
  # Import Donors: calls import method from the Donor model
  def import
    Donor.import(params[:file])
    redirect_to import_export_url, notice: "Donors imported."
  end
  
  # list all donors on index page
  def index
    @donors = Donor.all
    respond_to do |format|
      format.html
        format.pdf do
          pdf = DonorPdf.new(@donors)
          send_data pdf.render, filename: 'Donors.pdf', type: 'application/pdf'
        end
      end
  end
  
  # delete donor
  def destroy
    Donor.find(params[:id]).destroy
    flash[:success] = "Donor deleted."
    redirect_to donors_path
  end
  
  private
    # defines permitted and required parameters for create and update methods
    def donor_params
      params.required(:donor).permit(:first_name, :last_name, :address, :address2, :city,
       :state, :zip, :phone, :email, :notes)
    end
end

app/helpers/donors_helper.rb
 #----------------------------------#
  # Donors Controller Helper
  # original written by: Wei H, Oct 20 2016
  # major contributions by:
  #             Andy W, Oct 22 2016
  #----------------------------------#


module DonorsHelper
  
  # most methods below used on Surf Donors screens
  
  #returns the quantity of times a donor has made a donation
  def gift_count_per_donor(donor)
    selected_gifts = Gift.where(:donor_id => donor)
    selected_gifts.count
  end
  
  #returns the total dollar amount a donor has donated
  def gift_total_amount_per_donor(donor)
    selected_gifts = Gift.where(:donor_id => donor)
    sum = 0
    selected_gifts.each do |g|
      sum+=g.amount
    end
    return sum
  end
  
  #returns the last gift that a donor made, by created_at date
  def find_last_gift(donor)
    selected_gifts = Gift.where(:donor_id => donor)
    last_gift = nil
    selected_gifts.each do |g|
      if last_gift.nil?
        last_gift = g
      else
        if g.created_at > last_gift.created_at
          last_gift = g
        end
      end
    end 
    return last_gift
  end
  
  #returns the last gift $ amount a donor has given, or 0 if no 
  #gifts have been made
  def last_gift_amount(donor)
    last_gift = find_last_gift(donor)
    if last_gift.nil?
      return 0
    else
      return last_gift.amount
    end
  end
  
  #returns the last activity a donor gave for
  def last_activity(donor)
    last_gift = find_last_gift(donor)
    if last_gift.nil?
      return "--No gifts yet--"
    else
      return Activity.find(last_gift.activity_id).name
    end
  end
  
end

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  	<div class="row form-group">
  	   <%= render 'shared/donor_error_messages' %>
    	<div class="col-xs-2 col-xs-offset-2">
      	<%= f.label :first_name %>
      	<span class="required-field-marker">*</span>
        <%= f.text_field :first_name, class: 'form-control input-sm' %>
      </div>
      <div class="col-xs-2">
      	<%= f.label :last_name %>
      	<span class="required-field-marker">*</span>
        <%= f.text_field :last_name, class: 'form-control input-sm' %>
      </div>
    </div> <!-- row -->

    <div class="row form-group">
    	<div class="col-xs-4 col-xs-offset-2">
      	<%= f.label :address %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :address, class: 'form-control input-sm' %>
      </div>
    </div>   <!-- row -->

    <div class="row form-group">
     	<div class="col-xs-4 col-xs-offset-2">
      	<%= f.label :address2 %>
        <%= f.text_field :address2, class: 'form-control input-sm' %>
      </div>
    </div>   <!-- row -->

    <div class="row form-group">
      <div class="col-xs-2 col-xs-offset-2">
        <%= f.label :city %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :city, class: 'form-control input-sm' %>
      </div>
      <div class="col-xs-1">
      	<%= f.label :state %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :state, class: 'form-control input-sm' %>
      </div>

      <div class="col-xs-1">
      	<%= f.label :zip %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :zip, class: 'form-control input-sm' %>
      </div>
		</div>   <!-- row -->

		<div class="row form-group">
	    <div class="col-xs-2 col-xs-offset-2">
	        <%= f.label :email %>
	        <span class="required-field-marker">*</span>
	        <%= f.text_field :email, class: 'form-control input-sm' %>
	    </div>
	    <div class="col-xs-2">
	      <%= f.label :phone %>
	      <%= f.text_field :phone, class: 'form-control input-sm' %>
	    </div>
		</div>   <!-- row -->

		<div class=" row form-group">
      <div class="col-xs-8 col-xs-offset-1 text-center">
          <%= f.submit yield(:button_text), class: "btn btn-success" %>
        &nbsp;
        <%= link_to "Cancel", donors_path, class: "btn btn-danger" %>
      </div>
  	</div>   <!-- row -->
 	
 <% end %>

app/views/donors/edit.html.erb
<% provide(:title, "Edit Donor") %>
<% provide(:button_text, "Update") %>
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Edit Donor <small>&nbsp; Update this Donor or surf all donor gifts</small></h2>
  		<aside class="text-right">
  		  <div>
			      <span class="glyphicon glyphicon-plus icon-donna icon-donna-new"></span><span class="icon-donna-text"></span>
		        <%=link_to "Add New Gift for this Donor", new_gift_path(donor_id: @donor.id) %> 
  		  </div>
  		  <div>
      		Surf to: 
          		<%=link_to "All Gifts for this Donor", "/gifts?activity_id=&donor_id=" + @donor.id.to_s + "&commit=GO" %>
        </div>
        <div>
          <%= link_to "Delete donor", @donor, method: :delete,
                                                          data: { confirm: "Are you sure that you want to permanently remove this donor from the database? This action cannot be undone." } %>
        </div>
  		</aside>
  	</div>
  </div>
</div>
<div class="row">
  <%= render 'form' %>
</div>

app/views/donors/index.html.erb
<% provide(:title, "Surf Donors") %>
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Surf Donors <small>&nbsp; Select a row to view or edit that donor.</small></h2>
  		<aside class="text-right">
  		  <%= link_to(new_donor_path) do %>
			    <span class="glyphicon glyphicon-plus icon-donna icon-donna-new"></span><span class="icon-donna-text">New Donor</span>
		    <% end %>
  		  <div>
      		Surf to: 
          		<%=link_to "All Activities", activities_url %>
          		<%=link_to "All Gifts", gifts_url + "?activity_id=&donor_id=&commit=GO" %>
        </div>
  		</aside>
  	</div>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
    <% if @donors.count != 0 %>
    <table class="table table-striped table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <td>Name</td>
          <td>Gifts</td>
          <td>Total Gift</td>
          <td>Last Gift</td>
          <td>Last Activity</td>
        </tr>
      </thead>
      <tbody>
        <% @donors.each do |donor| %>
        <tr>
          <td><%= link_to "#{donor.first_name} #{donor.last_name}", edit_donor_path(donor) %></td>
          <td><%= link_to gift_count_per_donor(donor), "/gifts?donor_id=" + donor.id.to_s + "&activity_id=&commit=GO" %></td>
          <td>$<%= gift_total_amount_per_donor(donor) %></td>
          <td>$<%= last_gift_amount(donor) %></td>
          <td><%= last_activity(donor) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <h3>No donors yet.</h3>
    <% end %>
  </div>
</div>

app/views/donors/new.html.erb
<% provide(:title, "New Donor") %>
<% provide(:button_text, "Create") %>
<div class="row">
  <div class="col-sm-10 col-xs-offset-2">
  	<div class="page-header">
  		<h2>New Donor <small>&nbsp; Create a new Donor.</small></h2>
  	</div>
  </div>
</div>
<div class="row">
  <%=render 'form' %>
</div>