config/routes.rb
Rails.application.routes.draw do
  
  #----------------------------------#
  # Gift Garden Routes File
  # original written by: Andy W, Oct 14 2016
  # major contributions by:
  #             Wei H, Oct 16 2016
  #----------------------------------#
  
  resources :gifts, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :donors, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  resources :activities, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection { post :import }
  end
  
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/reports', to: 'static_pages#reports'
  get    '/import-export', to: 'static_pages#import_export'
  
  get    'hyper-surf/donors', to: 'hyper_surf#donors'
  get    'hyper-surf/all', to: 'hyper_surf#all'
  
  root 'static_pages#home'
end

app/models/activity.rb
class Activity < ApplicationRecord
  #----------------------------------#
  # Activities Model Definition
  # original written by: Andy W, Oct 13 2016
  # major contributions by:
  #             Wei H, Oct 15 2016
  #             Pat M, Oct 17 2016
  #----------------------------------#
  has_many :gifts, dependent: :destroy
  default_scope -> {order(created_at: :desc)}
  validates :name, presence: true, length: {maximum:255}
  validates :description, presence: true, length: {maximum:255}
  validates :goal, presence: true, :numericality => {:greater_than_or_equal_to => 0}
  
  def self.import(file)
    #CSV.foreach(file.path, headers: true) do |row|
    #  activity_hash = row.to_hash
    #  activity = Activity.where(id: activity_hash["id"])
    #  if activity.count == 1
    #    activity.first.update_attributes(activity_hash)
    #  else
    #    Activity.create!(activity_hash)
    #  end # end if !activity.nil?
    #end # end CSV.foreach
  end # end self.import(file)
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  #----------------------------------#
  # GiftGarden Activities Controller
  # original written by: Wei H, Oct 15 2016
  # major contributions by:
  #
  #----------------------------------#
  
  # defines a new activity
  def new
    @activity = Activity.new
  end
  
  # find activity by id and populate edit screen
  def edit
    @activity = Activity.find(params[:id])
  end
  
  #create new activity, or render edit page with errors list
  #activity_params defined in private below
  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      flash[:success] = "Activty added successfully!"
      redirect_to activities_url
    else
      render 'new'
    end
  end
  
  #update activity, or render edit page with errors list
  def update
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
       redirect_to activities_url
       flash[:success] = "Activty updated successfully!"
    else
      render 'edit'
    end
  end
  
  #list all activities on index page
  def index
    @activities = Activity.all
    respond_to do |format|
      format.html
        format.pdf do
          pdf = ActivityPdf.new(@activities)
          send_data pdf.render, filename: 'Activities.pdf', type: 'application/pdf'
        end
      end
  end
  
  #delete activity
  def destroy
    Activity.find(params[:id]).destroy
    flash[:success] = "Activity deleted."
    redirect_to activities_path
  end
  
  def import
    Activity.import(params[:file])
    redirect_to root_url, notice: "Activities imported."
  end
  
  private
    #define activity parameters accepted and required for create and update methods
    def activity_params
      params.required(:activity).permit(:name, :start_date, :end_date, :description,
       :goal, :notes)
    end
  
end

app/helpers/activities_helper.rb
 #----------------------------------#
  # Activities Controller Helper
  # original written by: Wei H, Oct 20 2016
  # major contributions by:
  #             Andy W, Oct 23 2016
  #----------------------------------#

module ActivitiesHelper
  
  #returns the percent value of the $ given vs the $ goal for an activity
  def progress(activity)
    selected_gifts = Gift.where(:activity_id => activity)
    sum = 0.0
    selected_gifts.each do |g|
      sum+=g.amount
    end
    return (sum/activity.goal).round(4)*100 unless activity.goal == 0
    return "N/A"
  end
  
  #returns the quantity of gifts given for an activity
  def gift_count_per_activity(activity)
    selected_gifts = Gift.where(:activity => activity)
    selected_gifts.count
  end 
  
  #returns the quantity of donors that have given $ for an activity
  def donor_count_per_activity(activity)
    selected_gifts = Gift.where(:activity_id => activity)
    selected_gifts.distinct.count(:donor_id)
  end 
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
    <div class="row form-group">
      <%= render 'shared/activity_error_messages' %>
      <div class="col-xs-6 col-xs-offset-2">
        <%= f.label :name %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :name, class: 'form-control input-sm' %> 
      </div>
    </div>
    <div class="row form-group">
      <div class="col-xs-2 col-xs-offset-2">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: 'form-control' %>
      </div>
      <div class="col-xs-2">
        <%= f.label :end_date %>
        <%= f.date_field :end_date, class: 'form-control' %>
      </div>
      <div class="col-xs-2">
        <%= f.label :goal %>
        <span class="required-field-marker">*</span>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :goal, class: 'form-control input-sm' %> 
        </div>
      </div>
    </div>
    
    <div class="row form-group">
      <div class="col-xs-6 col-xs-offset-2">
        <%= f.label :description %>
        <span class="required-field-marker">*</span>
        <%= f.text_field :description, class: 'form-control input-sm' %> 
      </div>
      <div class="col-xs-2"> &nbsp; </div>
    </div>

    <div class="row form-group">
      <div class="col-xs-6  col-xs-offset-2">
        <%= f.label :notes %></br>
        <%= f.text_area :notes, placeholder: "Enter notes here...", cols: "150", rows: "5", class: "form_control, input-sm" %>
      </div>
    </div>

    <div class="row form-group">
      <div class="col-xs-4 col-xs-offset-4 text-center">
        <%= f.submit yield(:button_text), class: "btn btn-success" %>
        &nbsp;
        <%= link_to "Cancel", activities_path, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>

app/views/activities/edit.html.erb
<% provide(:title, "Edit Activity") %>
<% provide(:button_text, "Update") %>
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Edit Activity <small>&nbsp; Update this Activity or surf its Gifts</small></h2>
  		<aside class="text-right">
  		  <div>
      		Surf to:
          		<%=link_to "All Gifts for this Activity", "/gifts?activity_id=" + @activity.id.to_s + "&donor_id=&commit=GO" %>
        </div>
        <div>
          <%= link_to "Delete activity", @activity, method: :delete,
                                                          data: { confirm: "Are you sure that you want to permanently remove this activity from the database? This action cannot be undone." } %>
        </div>
  		</aside>
  	</div>
  </div>
</div>
<div class="row">
  <%= render 'form' %>
</div>

app/views/activities/index.html.erb
<% provide(:title, "Surf Activities") %>
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
  	<div class="page-header">
  		<h2>Surf Activities <small>&nbsp; Select a row to view or edit that activty.</small></h2>
  		<aside class="text-right">
  		  <%= link_to(new_activity_path) do %>
			    <span class="glyphicon glyphicon-plus icon-donna icon-donna-new"></span><span class="icon-donna-text">New Activity</span>
		    <% end %>
  		  <div>
      		Surf to: 
      		  <%=link_to "All Donors", donors_url %>
          	<%=link_to "All Gifts", gifts_url + "?activity_id=&donor_id=&commit=GO" %>
        </div>
  		</aside>
  	</div>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
    <% if @activities.count != 0 %>
    <table class="table table-striped table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <td>Name</td>
          <td>End Date</td>
          <td>Goal</td>
          <td>Progress</td>
          <td>Donors</td>
          <td>Gifts</td>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
        <tr>
          <td><%= link_to activity.name, edit_activity_path(activity) %></td>
          <td><%= activity.end_date %></td>
          <td><%= number_to_currency(activity.goal) %></td>
          <td><%= progress(activity) %>%</td>
          <td><%= link_to donor_count_per_activity(activity), "/gifts?activity_id=" + activity.id.to_s + "&donor_id=&commit=GO" %></td>
          <td><%= link_to gift_count_per_activity(activity), "/gifts?activity_id=" + activity.id.to_s + "&donor_id=&commit=GO" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <h3>No activities yet.</h3>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<% provide(:title, "New Activity") %>
<% provide(:button_text, "Create Activity") %>
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
  	<div class="page-header">
  		<h2>New Activity <small>&nbsp; Create a new Activity.</small></h2>
  	</div>
  </div>
</div>
<div class="row">
  <%=render 'form' %>
</div>